# Generated by Django 4.2.1 on 2023-11-12 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usercomments'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='main.usercomments')),
            ],
        ),
    ]
