# Generated by Django 4.2.1 on 2023-11-12 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_likedposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomments',
            name='file',
            field=models.ImageField(upload_to='uploads\\post-pictures', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('gif', 'jpeg', 'png', 'ico', 'tiff', 'webp', 'eps', 'svg', 'psd', 'indd', 'cdr', 'ai', 'raw'))]),
        ),
        migrations.DeleteModel(
            name='LikedPosts',
        ),
    ]
